SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Schema')
BEGIN
	CREATE TABLE [dbo].[Views](
		[ViewId] [int] IDENTITY(1,1) NOT NULL,
		[PostId] [int] NOT NULL,
		[ViewDate] [datetime] NOT NULL,
		[PostUrl] [nvarchar](max) NULL,
	 CONSTRAINT [PK_dbo.Views] PRIMARY KEY CLUSTERED 
	(
		[ViewId] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END

GO
