//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sBlog.Net.Areas.Admin.Resources.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GenericResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GenericResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sBlog.Net.Areas.Admin.Resources.Views.Shared.GenericResources", typeof(GenericResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string CategoryMnuItem {
            get {
                return ResourceManager.GetString("CategoryMnuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string CommentMnuItem {
            get {
                return ResourceManager.GetString("CommentMnuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string DashboardMnuItem {
            get {
                return ResourceManager.GetString("DashboardMnuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log in.
        /// </summary>
        public static string LogInMnuItem {
            get {
                return ResourceManager.GetString("LogInMnuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log off.
        /// </summary>
        public static string LogOffMnuItem {
            get {
                return ResourceManager.GetString("LogOffMnuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Comments.
        /// </summary>
        public static string ManageCommentsMnuItem {
            get {
                return ResourceManager.GetString("ManageCommentsMnuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new page.
        /// </summary>
        public static string NewPageMnuItem {
            get {
                return ResourceManager.GetString("NewPageMnuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new post.
        /// </summary>
        public static string NewPostMnuItem {
            get {
                return ResourceManager.GetString("NewPostMnuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string PageMnuItem {
            get {
                return ResourceManager.GetString("PageMnuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        public static string PostMnuItem {
            get {
                return ResourceManager.GetString("PostMnuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string ProfileMnuItem {
            get {
                return ResourceManager.GetString("ProfileMnuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingMnuItem {
            get {
                return ResourceManager.GetString("SettingMnuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Sharing.
        /// </summary>
        public static string SocialSharingMnuItem {
            get {
                return ResourceManager.GetString("SocialSharingMnuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syn. Highlighter.
        /// </summary>
        public static string SyntaxHighlighterMnuItem {
            get {
                return ResourceManager.GetString("SyntaxHighlighterMnuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string TagMnuItem {
            get {
                return ResourceManager.GetString("TagMnuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploads.
        /// </summary>
        public static string UploadMnuItem {
            get {
                return ResourceManager.GetString("UploadMnuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Content Mgmt..
        /// </summary>
        public static string UserMgmtMnuItem {
            get {
                return ResourceManager.GetString("UserMgmtMnuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to visit blog.
        /// </summary>
        public static string VisitBlogMnuItem {
            get {
                return ResourceManager.GetString("VisitBlogMnuItem", resourceCulture);
            }
        }
    }
}
