//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sBlog.Net.Resources.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GenericResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GenericResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sBlog.Net.Resources.Views.Shared.GenericResources", typeof(GenericResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Page &gt;&gt;.
        /// </summary>
        public static string NextPageLink {
            get {
                return ResourceManager.GetString("NextPageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there are no posts in the page entered..
        /// </summary>
        public static string NoPostsMessage {
            get {
                return ResourceManager.GetString("NoPostsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted by &lt;b&gt;{0}&lt;/b&gt; under {1}.
        /// </summary>
        public static string PostNameCategoryInfo {
            get {
                return ResourceManager.GetString("PostNameCategoryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagged {0}.
        /// </summary>
        public static string PostTagInfo {
            get {
                return ResourceManager.GetString("PostTagInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; Previous Page.
        /// </summary>
        public static string PreviousPageLink {
            get {
                return ResourceManager.GetString("PreviousPageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to request an account.
        /// </summary>
        public static string RequestAcctLink {
            get {
                return ResourceManager.GetString("RequestAcctLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archives.
        /// </summary>
        public static string SideBarArchives {
            get {
                return ResourceManager.GetString("SideBarArchives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string SideBarCategories {
            get {
                return ResourceManager.GetString("SideBarCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Comments.
        /// </summary>
        public static string SideBarRecentComments {
            get {
                return ResourceManager.GetString("SideBarRecentComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Posts.
        /// </summary>
        public static string SideBarRecentPosts {
            get {
                return ResourceManager.GetString("SideBarRecentPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Options.
        /// </summary>
        public static string SideBarSiteOptions {
            get {
                return ResourceManager.GetString("SideBarSiteOptions", resourceCulture);
            }
        }
    }
}
